import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Suspense fallback={<div>loading</div>}> */}
        {children}
        {/* </Suspense>
        isy ye hoga ke jb koi chiz nhi aygi to wo loading kryga errror nhi dega loading dikhayga or os waqt tk kam ko rok kr rkhyga jb tk oski loading pori na ho jay */}
      </body>
    </html>
  );
}
